### ISSUE TITLE
[Docs] Missing DOCUMENTER_KEY in GitHub docs workflow

### ISSUE THREAD

**Issue by guilgautier** [dahtah/DPP.jl#3]
Hi guys,

FYI, some issues with the documentation might arise because of a missing `DOCUMENTER_KEY` field in the `.github/workflows/docs.yml` file

https://github.com/dahtah/DPP.jl/blob/8eac3652c750295d7dbc5726bc66e09aca43c8dd/.github/workflows/docs.yml#L25-L26

See documentation https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#GitHub-Actions

**Comment by dahtah** [comment]
Thanks Guillaume, I'm not sure what I'm supposed to do about this? I did generate a github token with the correct permissions, I think. There's no SSH deploy key as far as I'm aware, although I barely understand any of this and I'm hardly looking forward to learning more. If this doesn't work I'm leaning towards disabling CI altogether, it seems to be always more trouble than it's worth.

**Comment by guilgautier** [comment]
Got it, it doesn't seem to apply here.
